### ISSUE TITLE
Breaks in Chrome

### ISSUE THREAD

**Issue by tuckergordon** [dnozay/innersvg-polyfill#5]
While the polyfill works as expected with IE, it's breaking Google Chrome. With the polyfill installed, the following

```
const svg = document.createElementNS('http://www.w3.org/2000/svg', 'svg');
svg.innerHTML = '';
```
produces an error in Chrome:

> ERROR Error: Error parsing XML string
>     at SVGSVGElement.set (innersvg.js:82)

If I uninstall the polyfill, the error goes away

**Comment by willyboy** [comment]
Line 72 accidentally creates a global which breaks.
```
sXML = '<svg xmlns=\'http://www.w3.org/2000/svg\'>' + markupText + '</svg>';
var svgDocElement = dXML.parseFromString(sXML, 'text/xml').documentElement;
```
Should be
```
var sXML = '<svg xmlns=\'http://www.w3.org/2000/svg\'>' + markupText + '</svg>';
var svgDocElement = dXML.parseFromString(sXML, 'text/xml').documentElement;
```
